version: '2.4'

services:
  jupyter:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ./model.ipynb:/home/jovyan/model.ipynb
      - ./dataset_teeth:/home/jovyan/dataset_teeth
    mem_limit: 8g
    cpus: 4.0
    
